### ISSUE TITLE
Is it possible to create a user with password?

### ISSUE THREAD

**Issue by rmalenko** [Q-Technologies/puppet-local_users#2]
Hi,
Thank you.
Is it possible to create a user with password?

**Comment by mattqm** [comment]
This module will pass through the 'password' attribute unchanged.  So just set the password as you normally would for the user resource - which means encrypted for Linux/UNIX and plain text for Windows.  This module will only work via inputting the user info with hiera, therefore you cannot use convenience functions like pw_hash.

So hiera will be along these lines:

```
---
local_users::add::users:
  test_account:
    uid: 869
    gid: 800
    comment: 'Test Account'
    expiry: none
    password: '$6$kjkjskdj$MC6mq9yzkaAXqs.6JzCFLrGNfZYvBdUUhvl.0z4ZWDrhwrnw5ZcqsL08/t0YeguwMTi/h7LHfR1m6XHFpsWuQ0'
```
